version: 3
paths:
  only:
  ./cmd/mdatagen
  ./cmd/telemetrygen
  ./cmd/tracegen
  ./confmap/provider/s3provider
  ./exporter/googlecloudexporter
  ./exporter/googlecloudpubsubexporter
  ./exporter/googlemanagedprometheusexporter
  ./exporter/influxdbexporter
  ./exporter/mezmoexporter
  ./exporter/parquetexporter
  ./exporter/sumologicexporter
  ./extension/asapauthextension
  ./extension/basicauthextension
  ./extension/bearertokenauthextension
  ./extension/fluentbitextension
  ./extension/headerssetterextension
  ./extension/jaegerremotesampling
  ./extension/oauth2clientauthextension
  ./extension/observer
  ./extension/observer/ecsobserver
  ./extension/oidcauthextension
  ./extension/sigv4authextension
  ./extension/storage
  ./internal/aws/awsutil
  ./internal/aws/containerinsight
  ./internal/aws/cwlogs
  ./internal/aws/k8s
  ./internal/aws/metrics
  ./internal/aws/xray
  ./internal/aws/xray/testdata/sampleapp
  ./internal/aws/xray/testdata/sampleserver
  ./internal/common
  ./internal/coreinternal
  ./internal/docker
  ./internal/k8sconfig
  ./internal/metadataproviders
  ./internal/sharedcomponent
  ./internal/splunk
  ./internal/tools
  ./pkg/batchperresourceattr
  ./pkg/batchpersignal
  ./pkg/experimentalmetricmetadata
  ./pkg/ottl
  ./pkg/winperfcounters
  ./processor/datadogprocessor
  ./processor/deltatorateprocessor
  ./processor/metricsgenerationprocessor
  ./processor/redactionprocessor
  ./processor/schemaprocessor
  ./processor/servicegraphprocessor
  ./receiver/awsfirehosereceiver
  ./receiver/chronyreceiver
  ./receiver/cloudfoundryreceiver
  ./receiver/dotnetdiagnosticsre
